Development
PlutoIO/koenig pull request #2
Opened 2022-08-16 13:26 UTC by raudoc18

2022-08-16 13:49 UTC, Jauki requested changes
Personally i think that putting an the `AppFrame` into a completely new module is useless, because we already have such a module. We can add this module later... The Folder structure is not so clean IMO, i recommend you to watch this: [youtube](https://www.youtube.com/watch?v=Mm6_DlO5vvs) the only thing i dislike about this structure is that nearly every component is named ´index.ts´ as child. Maybe we can talk about this in the discussion chat... Another thing which i don't recommend you to do is the outsourcing of the types/interfaces. Besides this great job...

2022-08-16 13:49 UTC, Jauki commented on frontend/package.json
> +    "@raudoc18/pluto-appframe": "^0.1.0",
What is the purpose of the Appframe?

2022-08-16 13:49 UTC, Jauki commented on frontend/src/types/IAuthToken.d.ts
> +type IAuthToken = {
There is no such File/Directory needed for the types/interfaces because it is rendered in the `tsc`, i would recommend defining the interfaces/types above the function with an export, saves time...

2022-08-16 14:23 UTC, halelc18 commented on frontend/src/App.tsx
> +    <div className="desktop:grid desktop:grid-cols-10 h-[100vh] phone:px-4 phone:pt-10">
is there a reason for nopt using h-screen?

2022-08-16 14:58 UTC, halelc18 reviewed
I think that the folder structure is perfectly fine for this project. We should probably switch to the other structure in future bigger projects, but I don't think that it's neccessary to switch now. I also think that the types should be declared above the function and exported, because it's more convenient than switching through your files all the time. Besides that everything is fine 👍

2022-08-16 15:11 UTC, Jauki commented
> Personally i think that putting an the `AppFrame` into a completely new module is useless, because we already have such a module. We can add this module later... The Folder structure is not so clean IMO, i recommend you to watch this: [youtube](https://www.youtube.com/watch?v=Mm6_DlO5vvs) the only thing i dislike about this structure is that nearly every component is named ´index.ts´ as child. Maybe we can talk about this in the discussion chat... Another thing which i don't recommend you to do is the outsourcing of the types/interfaces. Besides this great job...

Another thing which both of you should do! @halelc18 @raudoc18 Please make sure to have a meaningfull PullRequest Name something like ´BIL-93: implementation .... ´

2022-08-16 15:11 UTC, Jauki commented
> I think that the folder structure is perfectly fine for this project. We should probably switch to the other structure in future bigger projects, but I don't think that it's neccessary to switch now. I also think that the types should be declared above the function and exported, because it's more convenient than switching through your files all the time. Besides that everything is fine 👍

Already discussed it with max and i think that having a scalable big folderstructure is more meaningfull...

2022-08-22 18:18 UTC, Jauki approved these changes

2022-08-22 18:20 UTC, halelc18 approved these changes

2022-08-22 18:27 UTC, merged