Bil 55
PlutoIO/koenig pull request #3
Opened 2022-08-24 11:29 UTC by raudoc18

2022-08-25 14:39 UTC, Jauki commented
Please make sure to add a good Title to your PR for Example -> BIL-55: Implementation Landing Screen, Login Screen

2022-08-25 16:03 UTC, Jauki requested changes

2022-08-25 16:03 UTC, Jauki commented on frontend/src/setup/api/useApi.ts
>  const baseURL = 'http://127.0.0.1:8000/api';
Maybe set in a dot env or as a proxy in the package.json

2022-08-26 11:12 UTC, raudoc18 commented on frontend/src/common/PrimaryButton.tsx
> +        to={props.to ? props.to : ''}
TS does not allow to put it in otherwise, I also tried to do it with an && exception, but that does not work either

2022-08-26 12:02 UTC, merged