BIL 54: Implement Signup Screen + BIL 64: Implement League Leaderboard Screen
PlutoIO/koenig pull request #4
Opened 2022-11-13 14:02 UTC by raudoc18

implementation:
+ added signup screen
+ added home screen
+ added TextInput component
+ refactored project structure
+ refactored context classes
+ refactored login page
+ documentation
- removed useAuth class

packages:
+ added formik
+ added framer-motion
- removed react-hook-form

TODO:
- TermsAndConditions animation
- Supabase implementation
- home page animations

2022-11-13 14:03 UTC, raudoc18 commented
this PR would be the new base for the development branch, as there were many fundamental changes

2022-11-14 18:09 UTC, Jauki requested changes
all in all great job :) <3

2022-11-14 18:09 UTC, Jauki commented on frontend/src/Performance chart.svg
> +<svg width="124" height="124" viewBox="0 0 124 124" fill="none" xmlns="http://www.w3.org/2000/svg">
Das sollt eig kein SVG sein müsst später dann irgenwie animiert werden sprich das des wir erstellen weil sich der score je nach performance verändert

2022-11-14 18:09 UTC, Jauki commented on frontend/src/common/Checkbox.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
hat normal keinen sinn mehr pls remove, weil es werden ja beide benutzt

2022-11-14 18:17 UTC, raudoc18 commented on frontend/src/Performance chart.svg
> +<svg width="124" height="124" viewBox="0 0 124 124" fill="none" xmlns="http://www.w3.org/2000/svg">
ja is eh klar, is derweil nur so a mock dings

2022-11-14 18:17 UTC, merged